### ISSUE TITLE
am i dumb? 

### ISSUE THREAD

**Issue by Devouredsoul** [taux1c/onlyfans-scraper#84]
whenever i type in the command 
onlyfans-scraper

all i get is 
zsh: command not found: onlyfans-scraper

**Comment by taux1c** [comment]
This doesn't work anymore. I haven't maintained it in a while. I don't personally use onlyfans and so this just took up too much of my time to bother with it. I did try accepting donations for a bit but people donated more than they could afford and then instead of asking for their money back  they would just dispute it which meant I had to pay a $30 fee plus refund the $10 donation. I later considered a membership based scraper and may eventually do that but not sure how many people would actually be interested in something like that.
